version: '3'
services: 
    jenkins:
        privileged: true
        user: root
        build: ./
        image: "jenkins-marvin"
        container_name: marvin-container
        environment: 
            USER_CHOCOLATEEN_PASSWORD: pac
            USER_VAUGIE_G_PASSWORD: vg
            USER_I_DONT_KNOW_PASSWORD: idk
            USER_NASSO_PASSWORD: nasso
        ports: 
            - "5000:8080"
        restart: always
        volumes:
            - ~/jenkins-volumes:/var/jenkins_home
            - ./jenkins.yml:/var/jenkins_home/casc_configs/jenkins.yml
            - /var/run/docker.sock:/var/run/docker.sock
            - /usr/local/bin/docker:/usr/local/bin/docker
