jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  remotingSecurity:
    enabled: true
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
              - "Hugo"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Build"
              - "Job/Workspace"
            assignments:
              - "Jeremy"
              - "Garance"
          - name: "gorilla"
            description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
            permissions:
              - "Job/Create"
              - "Job/Configure"
              - "Job/Read"
              - "Job/Delete"
            assignments:
              - "Garance"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Job/Read"
              - "Job/Workspace"
            assignments:
              - "Nassim"
  securityRealm:
    local:
      allowsSignup: false
      users:
      - id: "chocolateen"
        name: "Hugo"
        password: $USER_CHOCOLATEEN_PASSWORD
      - id: "vaugie_g"
        name: "Garance"
        password: $USER_VAUGIE_G_PASSWORD
      - id: "i_dont_know"
        name: "Jeremy"
        password: $USER_I_DONT_KNOW_PASSWORD
      - id: "nasso"
        name: "Nassim"
        password: $USER_NASSO_PASSWORD
jobs:
  - script: > 
      folder('Tools') {
        displayName("Tools")
          description("Folder for miscellaneous tools.")
      }